name: Local Deploy CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # 🧠 Uses your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate  # use `venv\Scripts\activate` on Windows
          pip install -r requirements.txt

      - name: Run FastAPI app
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 --reload
