name: Start FastAPI App

on:
  push:
    branches:
      - main

jobs:
  run-fastapi:
    runs-on: self-hosted  # Your local Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up virtual environment
        run: |
          python -m venv venv
          venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI app (CMD shell)
        run: |
          venv\Scripts\activate
          start /B uvicorn app.main:app --host 0.0.0.0 --port 8000
        shell: cmd

