name: Start FastAPI App

on:
  push:
    branches:
      - main

jobs:
  run-fastapi:
    runs-on: self-hosted  # Your local Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up virtual environment
        run: |
          python -m venv venv
          venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
